//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class degree
    {
        public degree()
        {
            this.artist = new HashSet<artist>();
        }
    
        public int id_degree { get; set; }

        [Required(ErrorMessage = "Поле повинне бути заповненим")]
        [StringLength(255, MinimumLength = 8, ErrorMessage = "Довжина стрічки не повинна бути меншою за 3 символи")]
        public string title { get; set; }

        [Required(ErrorMessage = "Поле повинне бути заповненим")]
        [Range(0.00, 100, ErrorMessage = "Допускаються числа від 0 до 100")]
        public double surcharge { get; set; }
    
        public virtual ICollection<artist> artist { get; set; }
    }
}
