//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rank
    {
        public rank()
        {
            this.artist = new HashSet<artist>();
        }
    
        public int id_rank { get; set; }
        public double surcharge { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<artist> artist { get; set; }
    }
}
