//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_card
    {
        public int id_rc { get; set; }
        public int id_report { get; set; }
        public double fees { get; set; }
        public int numder { get; set; }
        public string main_job { get; set; }
    
        public virtual report report { get; set; }
    }
}
