//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stage
    {
        public stage()
        {
            this.report = new HashSet<report>();
        }
    
        public int id_stage { get; set; }
        public int number { get; set; }
        public string time { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public int id_st { get; set; }
    
        public virtual ICollection<report> report { get; set; }
    }
}
