//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TemsTNTUEntities : DbContext
    {
        public TemsTNTUEntities()
            : base("name=TemsTNTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<artist> artist { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<degree> degree { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<rank> rank { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<report_card> report_card { get; set; }
        public virtual DbSet<stage> stage { get; set; }
        public virtual DbSet<state_topic> state_topic { get; set; }
    }
}
